name: ci

on:
  pull_request:
    branches:
      - 'master'
    types: [ labeled ]

jobs:
  docker:
    if: ${{ github.event.label.name == 'pushHub' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          file: ./Dockerfile
          tags: esdp2/gservicegroup:latest, esdp2/gservicegroup:${{ steps.date.outputs.date }}
