name: ci

on:
  pull_request:
    branches:
      - 'master'
    types: [labeled, closed]

jobs:
  labels:
    name: Label taking off
    if: github.event.label.name == 'pull request celery'
    runs-on: ubuntu-latest
    steps:

      - name: Take off label
        uses: actions/github-script@v1
        with:
          script: "github.issues.removeLabel({...context.issue, name: '${{ github.event.label.name }}' })"

  docker:
    if: github.event.label.name == 'pull request celery' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker gservicegroup
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile_celery
          tags: esdp2/celery:latest, esdp2/celery:${{ steps.date.outputs.date }}
